server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ZMS_ORDER?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 06494784
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG